name: Factions
version: 1.6.9.4
main: com.massivecraft.factions.P
authors: [Olof Larsson, Brett Flannigan]
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, CAPI, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag]
commands:
  factions:
    description: Spis komend Factions.
    aliases: [f]
permissions:
  factions.kit.admin:
    description: All faction permissions.
    children:
      factions.kit.mod: true
      factions.config: true
      factions.lock: true
      factions.reload: true
      factions.save: true
  factions.*:
    description: This is just an alias for factions.kit.admin
    children:
      factions.kit.admin: true
  factions.kit.mod:
    description: All faction permissions but configuration and persistance.
    children:
      factions.kit.halfmod: true
      factions.disband.any: true
      factions.setpeaceful: true
      factions.setpermanent: true
      factions.setpermanentpower: true
      factions.powerboost: true
      factions.sethome.any: true
      factions.money.*: true
      factions.join.any: true
      factions.join.others: true
      factions.admin.any: true
      factions.mod.any: true
  factions.kit.halfmod:
    description: Zones, bypassing, kicking, and chatspy
    children:
      factions.kit.fullplayer: true
      factions.managesafezone: true
      factions.managewarzone: true
      factions.bypass: true
      factions.kick.any: true
      factions.ownershipbypass: true
      factions.chatspy: true
  factions.kit.fullplayer:
    default: true
    description: Can also create new factions.
    children:
      factions.kit.halfplayer: true
      factions.create: true
  factions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      factions.admin: true
      factions.autoclaim: true
      factions.chat: true
      factions.claim: true
      factions.deinvite: true
      factions.description: true
      factions.disband: true
      factions.help: true
      factions.home: true
      factions.invite: true
      factions.join: true
      factions.kick: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.mod: true
      factions.money.kit.standard: true
      factions.noboom: true
      factions.open: true
      factions.owner: true
      factions.ownerlist: true
      factions.power: true
      factions.power.any: true
      factions.relation: true
      factions.sethome: true
      factions.show: true
      factions.tag: true
      factions.title: true
      factions.version: true
      factions.unclaim: true
      factions.unclaimall: true
  factions.admin:
    description: hand over your admin rights
  factions.admin.any:
    description: give or revoke admin status for any player in any faction
  factions.autoclaim:
    description: automatycznie zajmuj teren podczas chodzenia
  factions.bypass:
    description: enable admin bypass mode
  factions.chat:
    description: zmien tryb czatu
  factions.chatspy:
    description: enable admin chat spy mode
  factions.claim:
    description: zajmij teren tam gdzie stoisz
  factions.config:
    description: change a conf.json setting
  factions.create:
    description: zaloz nowe miasto
  factions.deinvite:
    description: usun oczekujace zaproszenie
  factions.description:
    description: zmien opis miasta
  factions.disband:
    description: rozwiaz maisto
  factions.disband.any:
    description: disband another faction
  factions.help:
    description: wyswietl pomoc
  factions.home:
    description: teleport to the faction home
  factions.invite:
    description: zapros gracza do swojego miasta
  factions.join:
    description: dolacz do miasta
  factions.join.any:
    description: join any faction, bypassing invitation process for closed factions
  factions.join.others:
    description: specify another player in the join command, to move them to the specified faction
  factions.kick:
    description: wyrzuc gracza z miasta
  factions.kick.any:
    description: kick anyone from any faction
  factions.leave:
    description: opusc miasto
  factions.list:
    description: zobacz liste miast
  factions.lock:
    description: lock all write stuff
  factions.managesafezone:
    description: claim land as a safe zone and build/destroy within safe zones
  factions.managewarzone:
    description: claim land as a war zone and build/destroy within war zones
  factions.map:
    description: show the territory map, and set optional auto update
  factions.mod:
    description: give or revoke moderator rights
  factions.mod.any:
    description: give or revoke moderator rights for any player in any faction
  factions.money.balance:
    description: show your factions current money balance
  factions.money.balance.any:
    description: show money balance for factions other than your own
  factions.money.deposit:
    description: wplac pieniadze do banku miasta
  factions.money.withdraw:
    description: wybierz pieniadze z banku miasta
  factions.money.withdraw.any:
    description: withdraw money from your factions other than your own
  factions.money.f2f:
    description: przelej pieniadze do innego miasta
  factions.money.f2p:
    description: przelej pieniadze z miasta do gracza
  factions.money.p2f:
    description: przelej pieniadze od gracza do miasta
  factions.money.kit.standard:
    children:
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  factions.money.*:
    children:
      factions.money.kit.standard: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.withdraw.any: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  factions.noboom:
    description: toggle explosions (peaceful factions only)
  factions.open:
    description: switch if invitation is required to join
  factions.owner:
    description: set ownership of claimed land
  factions.ownerlist:
    description: list owner(s) of this claimed land
  factions.ownershipbypass:
    description: bypass ownership restrictions within own faction's territory
  factions.setpeaceful:
    description: designate a faction as peaceful
  factions.setpermanent:
    description: designate a faction as permanent
  factions.setpermanentpower:
    description: set permanent power for a faction
  factions.power:
    description: show player power info
  factions.power.any:
    description: view an other players power level
  factions.powerboost:
    description: apply permanent power bonus/penalty to specified player or faction
  factions.relation:
    description: set relation wish to another faction
  factions.reload:
    description: reload data file(s) from disk
  factions.save:
    description: save all data to disk
  factions.sethome:
    description: set the faction home
  factions.sethome.any:
    description: set faction home for another faction
  factions.show:
    description: show faction information
  factions.tag:
    description: change the faction tag
  factions.title:
    description: set or remove a players title
  factions.version:
    description: see the version of the plugin
  factions.unclaim:
    description: unclaim the land where you are standing
  factions.unclaimall:
    description: unclaim all of your factions land