name: Factions
version: 1.6.9.4
main: com.massivecraft.factions.P
authors: [Olof Larsson, Brett Flannigan, translation Mistic92]
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, LWC, nChat, ChatManager, CAPI, AuthMe, Vault, Spout, WorldEdit, WorldGuard, AuthDB, CaptureThePoints, CombatTag]
commands:
  factions:
    description: Spis komend Factions.
    aliases: [f]
permissions:
  factions.kit.admin:
    description: All faction permissions.
    children:
      factions.kit.mod: true
      factions.config: true
      factions.lock: true
      factions.reload: true
      factions.save: true
  factions.*:
    description: This is just an alias for factions.kit.admin
    children:
      factions.kit.admin: true
  factions.kit.mod:
    description: All faction permissions but configuration and persistance.
    children:
      factions.kit.halfmod: true
      factions.disband.any: true
      factions.setpeaceful: true
      factions.setpermanent: true
      factions.setpermanentpower: true
      factions.powerboost: true
      factions.sethome.any: true
      factions.money.*: true
      factions.join.any: true
      factions.join.others: true
      factions.admin.any: true
      factions.mod.any: true
  factions.kit.halfmod:
    description: Zones, bypassing, kicking, and chatspy
    children:
      factions.kit.fullplayer: true
      factions.managesafezone: true
      factions.managewarzone: true
      factions.bypass: true
      factions.kick.any: true
      factions.ownershipbypass: true
      factions.chatspy: true
  factions.kit.fullplayer:
    default: true
    description: Can also create new factions.
    children:
      factions.kit.halfplayer: true
      factions.create: true
  factions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      factions.admin: true
      factions.autoclaim: true
      factions.chat: true
      factions.claim: true
      factions.claim.radius: true      
      factions.deinvite: true
      factions.description: true
      factions.disband: true
      factions.help: true
      factions.home: true
      factions.invite: true
      factions.join: true
      factions.kick: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.mod: true
      factions.money.kit.standard: true
      factions.noboom: true
      factions.open: true
      factions.owner: true
      factions.ownerlist: true
      factions.power: true
      factions.power.any: true
      factions.relation: true
      factions.sethome: true
      factions.show: true
      factions.tag: true
      factions.title: true
      factions.version: true
      factions.unclaim: true
      factions.unclaimall: true
  factions.admin:
    description: oddaj prawa burmistrza
  factions.admin.any:
    description: nadaj badz zabierz tytul burmistrza graczowi w miescie
  factions.autoclaim:
    description: automatycznie zajmuj teren podczas chodzenia
  factions.bypass:
    description: wlacz tryb omijania - tylko dla admuf
  factions.chat:
    description: zmien tryb czatu
  factions.chatspy:
    description: wlacz tryb szpiega - tyko dla admuf
  factions.claim:
    description: zajmij teren tam gdzie stoisz
  factions.claim.radius:
    description: zajmij teren w okreslonym promieniu
  factions.config:
    description: zmien conf.json - takie tam...
  factions.create:
    description: zaloz nowe miasto
  factions.deinvite:
    description: usun oczekujace zaproszenie
  factions.description:
    description: zmien opis miasta
  factions.disband:
    description: rozwiaz maisto
  factions.disband.any:
    description: rozwiaz inne miasto
  factions.help:
    description: wyswietl pomoc
  factions.home:
    description: teleport na spawn miasta
  factions.invite:
    description: zapros gracza do swojego miasta
  factions.join:
    description: dolacz do miasta
  factions.join.any:
    description: dolacz do wybranego miasta - tryb omijania dla adminow
  factions.join.others:
    description: wymusza dolaczenia gracza do wybranego miasta
  factions.kick:
    description: wyrzuc gracza z miasta
  factions.kick.any:
    description: wyrzuc kogokolwiek z jakiegokolwiek miasta
  factions.leave:
    description: opusc miasto
  factions.list:
    description: zobacz liste miast
  factions.lock:
    description: lock all write stuff
  factions.managesafezone:
    description: claim land as a safe zone and build/destroy within safe zones
  factions.managewarzone:
    description: claim land as a war zone and build/destroy within war zones
  factions.map:
    description: pokaz mape terenu i opcjonalnie ustaw na auto odswiezanie
  factions.mod:
    description: zabierz lub nadaj prawa zastepcy miasta
  factions.mod.any:
    description: zabierz lub nadaj prawa zastepny dowolnemu graczowi w dowolnym miescie
  factions.money.balance:
    description: zobacz czy hajs w miescie sie zgadza
  factions.money.balance.any:
    description: zobacz hajs innych miast
  factions.money.deposit:
    description: wplac pieniadze do banku miasta
  factions.money.withdraw:
    description: wybierz pieniadze z banku miasta
  factions.money.withdraw.any:
    description: wybierz pieniadze z banku innego miasta
  factions.money.f2f:
    description: przelej pieniadze do innego miasta
  factions.money.f2p:
    description: przelej pieniadze z miasta do gracza
  factions.money.p2f:
    description: przelej pieniadze od gracza do miasta
  factions.money.kit.standard:
    children:
      factions.money.balance: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  factions.money.*:
    children:
      factions.money.kit.standard: true
      factions.money.balance.any: true
      factions.money.deposit: true
      factions.money.withdraw: true
      factions.money.withdraw.any: true
      factions.money.f2f: true
      factions.money.f2p: true
      factions.money.p2f: true
  factions.noboom:
    description: toggle explosions (peaceful factions only)
  factions.open:
    description: zmien tryb miasta, zaproszenia wymagane lub nie
  factions.owner:
    description: ustaw wlasciciela zajetego terenu
  factions.ownerlist:
    description: zobacz liste wlascicieli zajetego terenu
  factions.ownershipbypass:
    description: bypass ownership restrictions within own faction's territory
  factions.setpeaceful:
    description: ustaw miasto jako przyjazne
  factions.setpermanent:
    description: ustaw miasto jako wieczne
  factions.setpermanentpower:
    description: set permanent power for a faction
  factions.power:
    description: zobacz moc gracza
  factions.power.any:
    description: zobacz moc innego gracza
  factions.powerboost:
    description: apply permanent power bonus/penalty to specified player or faction
  factions.relation:
    description: ustaw relacje z innym miastem
  factions.reload:
    description: reload data file(s) from disk
  factions.save:
    description: save all data to disk
  factions.sethome:
    description: ustaw spawn miasta
  factions.sethome.any:
    description: usatw spawn miasta dla innego miasta
  factions.show:
    description: zobacz informacje o miescie
  factions.tag:
    description: zmien tag miasta
  factions.title:
    description: ustaw lub usun tytul gracza
  factions.version:
    description: zobacz wersje pluginu
  factions.unclaim:
    description: zwolnij teren w miejscu gdzie stoisz
  factions.unclaimall:
    description: zwolnij tereny calego miasta